# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen

theme: advanced
plugins:
    - autolink
    - lists
    - spellchecker
    - pagebreak
    - style
    - table
    - advimage
    - advlink
    - preview
    - searchreplace
    - contextmenu
    - paste
    - nonbreaking
    - xhtmlxtras